Script started on Thu 01 Sep 2016 08:27:41 PM EDT
[root@localhost cs161]# cd ~curtis/[K[K[K[K[K[K[K/[K/cs161/root/
[root@localhost root]# ./sys161.c[K[K ler[K[K[Kkernel
sys161: System/161 release 1.14, compiled Aug 31 2016 13:47:29

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: po  p sb  /sbin/poweroff 
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 774800334 cycles (7122735k, 19u, 767677580i)
sys161: 3740 irqs 6 exns 0r/0w disk 29r/675w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 30.999042 seconds (24.9943 mhz)
sys161: Elapsed virtual time: 30.992013360 seconds (25 mhz)
[root@localhost root]# exit
exit

Script done on Thu 01 Sep 2016 08:28:53 PM EDT
